version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - ML_SERVICE_URL=http://ml-model:5000
    depends_on:
      - postgres
      - redis
      - ml-model
    networks:
      - neurabalancer-net

  ml-model:
    build:
      context: ./ml/model-server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./ml/models:/app/models
    networks:
      - neurabalancer-net

  postgres:
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_DB=neurabalancer
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - neurabalancer-net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - neurabalancer-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - neurabalancer-net

volumes:
  postgres-data:
  redis-data:

networks:
  neurabalancer-net:
    driver: bridge