env:
  - name: DB_HOST
    value: "timescaledb"
  - name: DB_PORT
    value: "5432"
  - name: DB_USER
    value: "admin"
  - name: DB_PASSWORD
    value: "password"
  - name: DB_NAME
    value: "metrics_db"
