name: CD Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Removing the problematic environment line
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Helm
      uses: azure/setup-helm@v3
    
    - name: Package Helm charts
      working-directory: ./deployments/helm
      run: |
        helm dependency update
        helm package .
    
    - name: Deploy to Kubernetes with ArgoCD
      uses: clowdhaus/argo-cd-action@v1.12.0
      with:
        command: app
        options: create neurabalancer --repo https://github.com/${{ github.repository }} --path deployments/helm --dest-server https://kubernetes.default.svc --dest-namespace default --values values-production.yaml
      env:
        ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
        ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_TOKEN }}